Enhanced Makefile such that it now can be used for development. Spell-checked manual page and made sure that all PDF files generate.

diff --git a/trunk/Makefile b/trunk/Makefile
--- a/trunk/Makefile
+++ b/trunk/Makefile
@@ -6,10 +6,6 @@
 TOP := 			.
 include 		config.mk
 
-config.mk: 		configure
-			echo "Have you run ./configure? Please do."
-			exit 1
-
 BINDIR      		:= $(PREFIX)/bin
 MAN1DIR     		:= $(PREFIX)/man/man1
 
@@ -31,22 +27,34 @@ clean:
 		rm -f *.cmo *.cmx *.o *.cmi *.ml *.mli *.mll *.mly
 		rm -f *.byte *.opt 
 		rm -f *.output *.annot
+		rm -f sample.mlb
+		rm -f *.aux *.inc *.tex *.log *.out *.pdf
 
 clobber: 	clean
-		rm -f config.mk
+		rm -f config.mk DEPEND
 
 
 install: 	ocamlburg.$(BINEXT) dirs
-		cp ocamlburg.$(BINEXT) $(BINDIR)/ocamlburg
-		cp ocamlburgfix $(BINDIR)
-		cp ocamlburgfix.1 $(MAN1DIR)
-		cp ocamlburg.1    $(MAN1DIR)
-		# todo: install runtime files camlburg.*
+		cp ocamlburg.$(BINEXT) 	$(BINDIR)/ocamlburg
+		cp ocamlburgfix   	$(BINDIR)
+		cp ocamlburgfix.1 	$(MAN1DIR)
+		cp ocamlburg.1    	$(MAN1DIR)
+		@echo "====================================================="
+		@echo "The following files are required by the code"
+		@echo "generated by OCamlburg. Please copy them manually"
+		@echo "to a location (like `$(OCAMLC) -where`) where"
+		@echo "the OCaml compiler can find them. The list of file:"
+		@echo camlburg.*
+		@echo "====================================================="
 		
 
-dirs: 		$(BINDIR) $(MAN1DIR)
+dirs: 		
 		test -d $(BINDIR)  || mkdir -p $(BINDIR)
-		test -d $(MAN1DIR) || mkdir -o $(MAN1DIR)
+		test -d $(MAN1DIR) || mkdir -p $(MAN1DIR)
+
+config.mk: 	configure
+		echo "Have you run ./configure? Please do."
+		exit 1
 
 
 # ------------------------------------------------------------------ 
@@ -118,18 +126,7 @@ MLI =		pretty.mli 	\
 		parseerror.mli	\
 		spec.mli	\
 
-NW := 		burg.nw 	\
-		camlburg.nw 	\
-		code.nw 	\
-		lex.nw 		\
-		main.nw 	\
-		mangler.nw 	\
-		noguardscheck.nw\
-		norm.nw 	\
-		parse.nw 	\
-		parseerror.nw 	\
-		sample.nw 	\
-		spec.nw 	\
+NW := 		$(wildcard *.nw)
 
 SCAN =		$(ML) $(MLI) \
 		camlburg.ml camlburg.mli\
@@ -138,6 +135,10 @@ SCAN =		$(ML) $(MLI) \
 
 CMO =		$(addsuffix .cmo,$(basename $(ML))) 
 CMX =		$(addsuffix .cmx,$(basename $(ML))) 
+
+TEX :=      	$(patsubst %.nw, %.tex, $(NW))
+INC :=      	$(patsubst %.nw, %.inc, $(NW))
+PDF :=      	$(patsubst %.nw, %.pdf, $(NW))
 
 # ------------------------------------------------------------------ 
 # binaries
@@ -170,6 +171,33 @@ runtime.opt:	camlburg.ml camlburg.cmx camlburg.cmi camlburg.mli camlburg.o
 
 examples.byte:	iburg.cmo sample.cmo sampleclient.cmo
 examples.opt:	iburg.cmx sample.cmx sampleclient.cmx
+
+# -- documentation
+
+RERUN =     Rerun (LaTeX|to get cross-references right)
+
+pdf:	    $(PDF)
+
+%.pdf:	%.tex 
+	    $(PDFLATEX) $<
+	    if egrep -s '$(RERUN)' $*.log ;then $(PDFLATEX) $<; fi
+	    if egrep -s '$(RERUN)' $*.log ;then $(PDFLATEX) $<; fi
+
+%.inc:      %.nw
+	    $(NOWEAVE) -delay $< > $@
+
+%.tex:	%.inc
+	    echo "    \documentclass[11pt]{article}	"  > $@
+	    echo "    \usepackage{hyperref}		" >> $@
+	    echo "    \usepackage{noweb}		" >> $@
+	    echo "    \usepackage{xspace}		" >> $@
+	    echo "    \noweboptions{breakcode}		" >> $@
+	    echo "    \begin{document}			" >> $@
+	    echo "    \def\ocaml{OCaml\xspace}		" >> $@	
+	    echo "    \let\module\texttt		" >> $@	
+	    echo "    \input{$<}			" >> $@
+	    echo "    \end{document}			" >> $@
+
 
 # ------------------------------------------------------------------ 
 # dependencies
